# banner图配置开启或关闭
spring:
  main:
    banner-mode: console
    # 指定配置文件
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/socks?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.18.137
    port: 6379
    password: 123
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    connect-timeout: 30000
    # 连接超时时间（毫秒）
    timeout: 10000

# 配置swagger开启关闭
swagger.show: true

# 指定端口
server:
  port: 9999
# mybatis-plus打印sql语句日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eyes:
  url: https://open.api.tianyancha.com/services/open/m/bids/2.0?
  url1: https://open.api.tianyancha.com/services/open/ic/baseinfoV2/2.0?
  token: 120dc8fe-d9eb-47ac-a32b-92ee0d7c36e2
