# banner图配置开启或关闭
spring:
  main:
    banner-mode: console
    # 指定配置文件
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/socks?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.18.137
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 30000
# 指定端口
server:
  port: 9999
# mybatis-plus打印sql语句日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
